### ISSUE TITLE
Duplicate SMEMA Machine Ready States after Saving

### ISSUE THREAD

**Issue by Industry4** [Industry4/MultiPlug.Ext.Hermes#114]
### Bug
Duplicate SMEMA Machine Ready States after Saving on the following pages:
- **_/extensions/multiplug.ext.hermes/lane/upstream/smema/_**
- **_/extensions/multiplug.ext.hermes/lane/upstream/smema/subscription/_**

### Screenshot
![image](https://github.com/Industry4/MultiPlug.Ext.Hermes/assets/14904422/36b67ec6-972b-4896-a944-1990c9736dfb)

### Workaround

- This doesn't seem to effect runtime. All duplicate States change at the same time.
- The issue is resolved after software reboot

**Comment by HaakonAxxe** [comment]
I have seen the samme issue at our site with duplicates.

**Comment by Industry4** [comment]
This is available in 1.0.24 https://github.com/Industry4/MultiPlug.Ext.Hermes/releases/tag/1.0.24
