### ISSUE TITLE
Validate Scan Station Data

### ISSUE THREAD

**Issue by Industry4** [Industry4/MultiPlug.Ext.Hermes#45]
In order to prompt the user that the injected Scan Station data is bad, data inserted should be checked for known bad values.
For Example

- NOSCAN
- ERROR
- EMPTY
- NOT FOUND

These should be settable, and when to prompt the user should also be settable

- On Injection
- On Use

**Comment by leeder269** [comment]
I would recommend to add a detection for double scan as well.

**Comment by Industry4** [comment]
@leeder269  Thanks for your comment, this will be considered. You also might also want to consider setting the scan queue length to 1, this was added in version 1.0.12, more information here: #44

**Comment by Industry4** [comment]
### Data Validation
/extensions/multiplug.ext.hermes/lane/scanstation/datasource/

This currently occurs **On Use** - ie When it is taken out of the Scan Station Queue
![image](https://user-images.githubusercontent.com/14904422/232255088-47fe974e-015d-47ed-8657-3fb59947f740.png)

The Scan Station will show the **Verification** status as **Bad**. It has to be manually deleted.
![image](https://user-images.githubusercontent.com/14904422/232255976-fe4ed6b7-3a26-4e58-82bc-1f3a7192f3d9.png)
